
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jul 26 15:26:27 CEST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PIPE = 20;
  public static final int EUROKM = 12;
  public static final int CM = 21;
  public static final int KMH = 6;
  public static final int RO = 24;
  public static final int S = 22;
  public static final int FLOAT_TYPE = 31;
  public static final int PRICE = 30;
  public static final int COMPUTE = 9;
  public static final int COL = 23;
  public static final int DISC = 15;
  public static final int RC = 25;
  public static final int EURO = 14;
  public static final int SO = 26;
  public static final int PERC = 11;
  public static final int EOF = 0;
  public static final int TIME = 16;
  public static final int EXTRA = 18;
  public static final int SEP = 8;
  public static final int error = 1;
  public static final int ARROW = 7;
  public static final int TOKEN3 = 4;
  public static final int TOKEN2 = 3;
  public static final int EQ = 19;
  public static final int TOKEN1 = 2;
  public static final int LINE = 13;
  public static final int UINT = 29;
  public static final int QSTRING = 28;
  public static final int SC = 27;
  public static final int EXPENSE = 17;
  public static final int KM = 5;
  public static final int TO = 10;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[20]=new String("PIPE");
		TT[12]=new String("EUROKM");
		TT[21]=new String("CM");
		TT[6]=new String("KMH");
		TT[24]=new String("RO");
		TT[22]=new String("S");
		TT[31]=new String("FLOAT_TYPE");
		TT[30]=new String("PRICE");
		TT[9]=new String("COMPUTE");
		TT[23]=new String("COL");
		TT[15]=new String("DISC");
		TT[25]=new String("RC");
		TT[14]=new String("EURO");
		TT[26]=new String("SO");
		TT[11]=new String("PERC");
		TT[0]=new String("EOF");
		TT[16]=new String("TIME");
		TT[18]=new String("EXTRA");
		TT[8]=new String("SEP");
		TT[1]=new String("error");
		TT[7]=new String("ARROW");
		TT[4]=new String("TOKEN3");
		TT[3]=new String("TOKEN2");
		TT[19]=new String("EQ");
		TT[2]=new String("TOKEN1");
		TT[13]=new String("LINE");
		TT[29]=new String("UINT");
		TT[28]=new String("QSTRING");
		TT[27]=new String("SC");
		TT[17]=new String("EXPENSE");
		TT[5]=new String("KM");
		TT[10]=new String("TO");
	}
public String getTT(int i){return TT[i];}
}
