/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;
 

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>scanner.jflex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\35\1\34\1\74\1\74\1\33\22\0\1\35\1\0\1\36"+
    "\1\61\1\31\1\73\1\32\1\0\1\67\1\70\2\0\1\66\1\7"+
    "\1\56\1\57\1\23\1\12\1\10\1\14\1\25\1\15\1\16\1\11"+
    "\1\17\1\24\1\22\1\60\1\0\1\65\1\64\2\0\1\50\1\21"+
    "\1\37\1\51\1\44\1\13\2\20\1\45\3\20\1\40\1\46\1\3"+
    "\1\41\1\20\1\47\1\2\1\43\1\42\2\20\1\4\1\5\1\6"+
    "\4\0\1\1\1\0\1\26\2\21\1\13\1\52\1\13\1\20\1\63"+
    "\2\20\1\62\1\20\1\27\1\20\1\55\1\30\1\20\1\54\2\20"+
    "\1\53\5\20\1\71\1\0\1\72\7\0\1\74\u1fa2\0\1\74\1\74"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\3\3\1\1\1\3\1\4\1\3"+
    "\2\1\2\5\10\1\1\6\2\1\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\3\0\1\16\1\0\2\3"+
    "\1\0\1\17\3\3\1\0\1\3\4\0\1\20\1\0"+
    "\1\21\1\0\1\22\4\0\1\17\1\0\1\23\1\24"+
    "\1\0\2\3\11\0\2\20\6\0\1\25\3\0\1\3"+
    "\12\0\1\26\2\0\1\27\1\30\1\17\1\31\2\0"+
    "\5\32\1\20\2\0\1\33\2\0\1\32\13\0\1\20"+
    "\1\34\1\35\1\36\1\37\4\0\1\37\2\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\267\0\364\0\u0131\0\u016e\0\u01ab"+
    "\0\75\0\u01e8\0\u0225\0\u0262\0\u029f\0\75\0\u02dc\0\u0319"+
    "\0\u0356\0\u0393\0\u03d0\0\u040d\0\u044a\0\u0487\0\75\0\u04c4"+
    "\0\u0501\0\75\0\75\0\75\0\75\0\75\0\75\0\75"+
    "\0\u053e\0\u057b\0\u05b8\0\75\0\u05f5\0\u0632\0\u066f\0\u06ac"+
    "\0\u044a\0\u06e9\0\u0726\0\u0763\0\u016e\0\u07a0\0\u07dd\0\u081a"+
    "\0\u0857\0\u0894\0\u08d1\0\u02dc\0\75\0\u090e\0\75\0\u094b"+
    "\0\u0988\0\u09c5\0\u0a02\0\u0a3f\0\u0a7c\0\75\0\u0ab9\0\u0af6"+
    "\0\u0b33\0\u0b70\0\u0bad\0\u0bea\0\u0c27\0\u0c64\0\u0ca1\0\u0cde"+
    "\0\u0d1b\0\u0d58\0\u0d95\0\u0dd2\0\u0e0f\0\u0e4c\0\u0e89\0\u0ec6"+
    "\0\u0f03\0\u0f40\0\u0f7d\0\u0fba\0\u0ff7\0\u1034\0\u1071\0\u10ae"+
    "\0\u10eb\0\u1128\0\u1165\0\u11a2\0\u11df\0\u121c\0\u1259\0\u1296"+
    "\0\u12d3\0\u1310\0\75\0\u134d\0\u138a\0\75\0\u13c7\0\u0fba"+
    "\0\75\0\u1404\0\u1441\0\u147e\0\u14bb\0\u14f8\0\u1535\0\u1572"+
    "\0\u15af\0\u15ec\0\u1629\0\75\0\u1666\0\u16a3\0\75\0\u16e0"+
    "\0\u171d\0\u175a\0\u1797\0\u17d4\0\u1811\0\u184e\0\u188b\0\u18c8"+
    "\0\u1905\0\u1942\0\u197f\0\75\0\75\0\75\0\u19bc\0\u19f9"+
    "\0\u1a36\0\u1a73\0\u1ab0\0\75\0\u1aed\0\u1b2a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\7\2\1\3\1\4\1\5\1\6\1\7\1\10\3\5"+
    "\1\2\1\7\1\11\1\12\1\5\1\10\1\7\2\2"+
    "\1\13\1\14\1\15\2\16\1\17\1\20\3\2\1\21"+
    "\1\22\3\2\1\7\1\23\1\24\3\2\1\25\1\26"+
    "\1\27\1\30\1\31\2\2\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\106\0\1\41\1\42\1\43\5\42"+
    "\1\0\1\42\1\0\4\42\10\0\1\42\4\0\1\42"+
    "\3\0\3\42\11\0\1\44\11\0\1\45\6\0\1\5"+
    "\1\46\1\5\1\43\1\5\1\47\2\46\1\0\1\43"+
    "\1\50\1\5\1\46\1\5\1\43\10\0\1\43\4\0"+
    "\1\43\3\0\3\43\3\0\1\51\17\0\1\45\6\0"+
    "\3\46\1\43\4\46\1\0\1\43\1\0\3\46\1\43"+
    "\10\0\1\43\4\0\1\43\3\0\3\43\3\0\1\51"+
    "\17\0\1\45\6\0\1\52\1\53\1\54\1\55\3\56"+
    "\1\5\1\0\1\55\1\50\1\54\1\5\1\56\1\55"+
    "\10\0\1\55\4\0\1\55\3\0\3\55\3\0\1\51"+
    "\17\0\1\45\6\0\10\43\1\0\1\43\1\0\4\43"+
    "\10\0\1\43\4\0\1\43\3\0\3\43\23\0\1\45"+
    "\6\0\3\46\1\43\4\46\1\0\1\43\1\50\3\46"+
    "\1\43\10\0\1\43\4\0\1\43\3\0\3\43\3\0"+
    "\1\51\17\0\1\45\6\0\3\57\1\43\1\57\1\60"+
    "\2\57\1\0\1\43\1\0\1\57\1\61\1\57\1\43"+
    "\10\0\1\43\4\0\1\43\3\0\3\43\3\0\1\51"+
    "\47\0\1\62\75\0\1\63\76\0\1\16\40\0\36\64"+
    "\1\65\36\64\1\0\1\45\1\0\1\66\4\0\10\43"+
    "\1\0\1\43\1\0\4\43\10\0\1\43\4\0\1\43"+
    "\3\0\3\43\25\0\1\67\41\0\1\70\30\0\1\45"+
    "\2\0\1\71\3\0\10\43\1\0\1\43\1\0\4\43"+
    "\10\0\1\43\4\0\1\43\3\0\3\43\23\0\1\45"+
    "\6\0\10\43\1\0\1\43\1\0\4\43\10\0\1\43"+
    "\4\0\1\43\1\72\2\0\3\43\23\0\1\45\6\0"+
    "\10\43\1\0\1\43\1\0\4\43\10\0\1\43\4\0"+
    "\1\43\3\0\3\43\1\73\31\0\3\74\1\0\4\74"+
    "\3\0\3\74\56\0\1\75\146\0\1\76\42\0\1\77"+
    "\46\0\1\45\6\0\3\42\1\0\3\42\4\0\1\42"+
    "\1\0\1\42\50\0\1\45\74\0\1\45\6\0\10\42"+
    "\1\0\1\42\1\0\4\42\10\0\1\42\4\0\1\42"+
    "\3\0\3\42\24\0\5\100\4\0\1\100\4\0\2\100"+
    "\4\0\3\100\6\0\17\100\4\0\2\100\12\0\1\45"+
    "\6\0\3\101\1\42\4\101\1\0\1\42\1\0\3\101"+
    "\1\42\10\0\1\42\4\0\1\42\3\0\3\42\3\0"+
    "\1\51\17\0\1\45\6\0\1\46\1\101\1\46\1\42"+
    "\2\46\1\102\1\101\1\0\1\42\1\0\1\46\1\101"+
    "\1\46\1\42\10\0\1\42\4\0\1\42\3\0\3\42"+
    "\3\0\1\51\26\0\1\103\1\0\1\103\1\0\2\103"+
    "\5\0\1\103\1\0\1\103\50\0\1\45\6\0\3\46"+
    "\1\43\4\46\1\0\1\43\1\104\3\46\1\43\10\0"+
    "\1\43\4\0\1\43\3\0\3\43\3\0\1\51\17\0"+
    "\1\45\6\0\3\46\1\43\4\46\1\0\1\43\1\105"+
    "\3\46\1\43\10\0\1\43\4\0\1\43\3\0\3\43"+
    "\3\0\1\51\17\0\1\45\6\0\3\46\1\43\4\46"+
    "\1\0\1\43\1\106\3\46\1\43\10\0\1\43\4\0"+
    "\1\43\3\0\3\43\3\0\1\51\17\0\1\45\6\0"+
    "\3\46\1\43\4\46\1\0\1\43\1\107\3\46\1\43"+
    "\10\0\1\43\4\0\1\43\3\0\3\43\3\0\1\51"+
    "\17\0\1\45\6\0\3\110\1\42\4\110\1\0\1\42"+
    "\1\0\3\110\1\42\10\0\1\42\4\0\1\42\3\0"+
    "\3\42\3\0\1\51\17\0\1\45\6\0\3\110\1\42"+
    "\4\110\1\0\1\42\1\111\3\110\1\42\10\0\1\42"+
    "\4\0\1\42\3\0\3\42\3\0\1\51\17\0\1\45"+
    "\6\0\3\110\1\42\4\110\1\0\1\42\1\112\3\110"+
    "\1\42\10\0\1\42\4\0\1\42\3\0\3\42\3\0"+
    "\1\51\30\0\1\113\10\0\1\62\54\0\1\114\1\115"+
    "\130\0\1\116\74\0\1\117\75\0\1\120\1\0\1\121"+
    "\33\0\1\122\146\0\1\123\30\0\3\124\1\0\4\124"+
    "\3\0\3\124\47\0\7\75\1\125\65\75\57\0\1\126"+
    "\17\0\5\127\4\0\1\127\4\0\2\127\4\0\3\127"+
    "\6\0\17\127\4\0\2\127\12\0\1\45\6\0\3\130"+
    "\1\0\4\130\3\0\3\130\30\0\1\51\17\0\1\45"+
    "\6\0\3\101\1\0\4\101\1\0\1\42\1\0\3\101"+
    "\1\42\10\0\1\42\10\0\1\42\5\0\1\51\26\0"+
    "\3\131\1\0\4\131\3\0\3\131\57\0\1\132\1\0"+
    "\1\132\1\0\2\132\5\0\1\132\1\0\1\132\57\0"+
    "\1\133\1\0\1\133\1\0\1\133\6\0\1\133\1\0"+
    "\1\134\57\0\1\135\1\0\1\135\1\0\2\135\5\0"+
    "\1\135\1\0\1\135\57\0\1\133\1\0\1\133\1\0"+
    "\2\133\5\0\1\133\1\0\1\133\50\0\1\45\6\0"+
    "\3\136\1\0\4\136\3\0\3\136\30\0\1\51\26\0"+
    "\1\103\1\0\1\103\1\0\1\103\6\0\1\103\1\0"+
    "\1\137\57\0\1\140\3\0\2\135\7\0\1\135\61\0"+
    "\1\141\10\0\1\113\55\0\1\115\73\0\1\114\132\0"+
    "\1\142\77\0\1\143\74\0\1\144\77\0\1\145\64\0"+
    "\1\146\112\0\1\147\27\0\3\150\1\0\4\150\3\0"+
    "\3\150\47\0\7\75\1\125\47\75\1\16\15\75\63\0"+
    "\1\151\13\0\5\152\4\0\1\152\4\0\2\152\4\0"+
    "\3\152\6\0\17\152\4\0\2\152\21\0\3\130\1\0"+
    "\4\130\3\0\3\130\30\0\1\51\46\0\1\153\54\0"+
    "\3\154\1\0\4\154\3\0\3\154\57\0\3\155\1\0"+
    "\4\155\3\0\3\155\57\0\1\155\1\0\1\155\1\0"+
    "\1\156\6\0\1\155\61\0\3\157\1\0\4\157\3\0"+
    "\3\157\57\0\3\136\1\0\4\136\3\0\3\136\30\0"+
    "\1\51\26\0\1\131\1\0\1\131\1\0\1\131\6\0"+
    "\1\131\61\0\2\157\1\160\1\0\4\157\4\0\2\157"+
    "\61\0\1\161\10\0\1\141\113\0\1\162\100\0\1\163"+
    "\76\0\1\164\103\0\1\165\17\0\5\166\4\0\1\166"+
    "\4\0\2\166\4\0\3\166\6\0\17\166\4\0\2\166"+
    "\40\0\1\167\67\0\1\170\5\0\1\153\66\0\1\170"+
    "\74\0\1\171\74\0\1\170\3\0\1\153\70\0\1\172"+
    "\3\0\1\153\60\0\1\173\10\0\1\161\114\0\1\174"+
    "\33\0\1\175\154\0\1\176\14\0\5\177\4\0\1\177"+
    "\4\0\2\177\4\0\3\177\6\0\17\177\4\0\2\177"+
    "\21\0\1\200\1\0\1\200\1\0\2\200\5\0\1\200"+
    "\1\0\1\200\57\0\1\200\1\0\1\200\1\0\1\201"+
    "\6\0\1\200\61\0\1\200\1\0\1\202\1\0\2\200"+
    "\7\0\1\200\61\0\1\203\10\0\1\173\115\0\1\204"+
    "\74\0\1\205\57\0\1\206\46\0\1\207\5\166\4\0"+
    "\1\166\4\0\2\166\4\0\3\166\6\0\17\166\4\0"+
    "\2\166\21\0\3\167\1\0\4\167\3\0\3\167\57\0"+
    "\1\167\1\0\1\167\1\0\1\167\6\0\1\167\1\0"+
    "\1\167\57\0\2\167\2\0\4\167\4\0\2\167\72\0"+
    "\1\203\53\0\1\210\1\0\1\211\73\0\1\212\76\0"+
    "\1\213\71\0\1\214\77\0\1\211\1\215\74\0\1\216"+
    "\72\0\1\214\1\0\1\215\66\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7015];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\1\11\4\1\1\11\10\1\1\11"+
    "\2\1\7\11\3\0\1\11\1\0\2\1\1\0\4\1"+
    "\1\0\1\1\4\0\1\1\1\0\1\11\1\0\1\11"+
    "\4\0\1\1\1\0\1\11\1\1\1\0\2\1\11\0"+
    "\2\1\6\0\1\1\3\0\1\1\12\0\1\11\2\0"+
    "\1\11\2\1\1\11\2\0\6\1\2\0\1\11\2\0"+
    "\1\11\13\0\1\1\3\11\1\1\4\0\1\11\2\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	private Symbol sym(int type) {
		return new Symbol(type, yyline, yycolumn);
	}
 
	private Symbol sym(int type, Object value) {
		return new Symbol(type, yyline, yycolumn, value);
	}
 


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 214) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Scanner Error: " + yytext());
            }
          case 32: break;
          case 2: 
            { return sym(sym.LINE);
            }
          case 33: break;
          case 3: 
            { return sym(sym.UINT, new Integer(yytext()));
            }
          case 34: break;
          case 4: 
            { return sym(sym.COL);
            }
          case 35: break;
          case 5: 
            { ;
            }
          case 36: break;
          case 6: 
            { return sym(sym.S);
            }
          case 37: break;
          case 7: 
            { return sym(sym.EQ);
            }
          case 38: break;
          case 8: 
            { return sym(sym.CM);
            }
          case 39: break;
          case 9: 
            { return sym(sym.RO);
            }
          case 40: break;
          case 10: 
            { return sym(sym.RC);
            }
          case 41: break;
          case 11: 
            { return sym(sym.SO);
            }
          case 42: break;
          case 12: 
            { return sym(sym.SC);
            }
          case 43: break;
          case 13: 
            { return sym(sym.PERC);
            }
          case 44: break;
          case 14: 
            { return sym(sym.ARROW);
            }
          case 45: break;
          case 15: 
            { return sym(sym.FLOAT_TYPE, new Float(yytext()));
            }
          case 46: break;
          case 16: 
            { return sym(sym.TOKEN3);
            }
          case 47: break;
          case 17: 
            { return sym(sym.QSTRING, yytext());
            }
          case 48: break;
          case 18: 
            { return sym(sym.TO);
            }
          case 49: break;
          case 19: 
            { return sym(sym.SEP);
            }
          case 50: break;
          case 20: 
            { return sym(sym.KM);
            }
          case 51: break;
          case 21: 
            { return sym(sym.PRICE,new Float(yytext()));
            }
          case 52: break;
          case 22: 
            { return sym(sym.TIME);
            }
          case 53: break;
          case 23: 
            { return sym(sym.DISC);
            }
          case 54: break;
          case 24: 
            { return sym(sym.EURO);
            }
          case 55: break;
          case 25: 
            { return sym(sym.KMH);
            }
          case 56: break;
          case 26: 
            { return sym(sym.TOKEN2);
            }
          case 57: break;
          case 27: 
            { return sym(sym.EXTRA);
            }
          case 58: break;
          case 28: 
            { return sym(sym.COMPUTE);
            }
          case 59: break;
          case 29: 
            { return sym(sym.EXPENSE);
            }
          case 60: break;
          case 30: 
            { return sym(sym.EUROKM);
            }
          case 61: break;
          case 31: 
            { return sym(sym.TOKEN1);
            }
          case 62: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
